version : '3'
services:
  xueyi-nacos:
    container_name: xueyi-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
    depends_on:
      - xueyi-mysql
  xueyi-mysql:
    container_name: xueyi-mysql
    image: mysql:8.0
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'xy-cloud'
      MYSQL_ROOT_PASSWORD: password
  xueyi-redis:
    container_name: xueyi-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/xueyi/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/xueyi/redis/redis.conf
  xueyi-nginx:
    container_name: xueyi-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/xueyi/projects/xueyi-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - xueyi-gateway
    links:
      - xueyi-gateway
  xueyi-gateway:
    container_name: xueyi-gateway
    build:
      context: ./xueyi/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - xueyi-redis
    links:
      - xueyi-redis
  xueyi-auth:
    container_name: xueyi-auth
    build:
      context: ./xueyi/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - xueyi-redis
    links:
      - xueyi-redis
  xueyi-modules-tenant:
    container_name: xueyi-modules-tenant
    build:
      context: ./xueyi/modules/tenant
      dockerfile: dockerfile
    ports:
      - "9700:9700"
    depends_on:
      - xueyi-redis
      - xueyi-mysql
    links:
      - xueyi-redis
      - xueyi-mysql
  xueyi-modules-system:
    container_name: xueyi-modules-system
    build:
      context: ./xueyi/modules/system
      dockerfile: dockerfile
    ports:
      - "9600:9600"
    depends_on:
      - xueyi-redis
      - xueyi-mysql
    links:
      - xueyi-redis
      - xueyi-mysql
  xueyi-modules-gen:
    container_name: xueyi-modules-gen
    build:
      context: ./xueyi/modules/gen
      dockerfile: dockerfile
    ports:
      - "9400:9400"
    depends_on:
      - xueyi-mysql
    links:
      - xueyi-mysql
  xueyi-modules-job:
    container_name: xueyi-modules-job
    build:
      context: ./xueyi/modules/job
      dockerfile: dockerfile
    ports:
      - "9500:9500"
    depends_on:
      - xueyi-mysql
    links:
      - xueyi-mysql
  xueyi-modules-file:
    container_name: xueyi-modules-file
    build:
      context: ./xueyi/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./xueyi/uploadPath:/home/xueyi/uploadPath
  xueyi-visual-monitor:
    container_name: xueyi-visual-monitor
    build:
      context: ./xueyi/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
